# Generated by Django 4.2.19 on 2025-03-04 23:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, unique=True)),
                ('client_logo', models.ImageField(blank=True, null=True, upload_to='clients/client_logo')),
                ('client_website', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name': 'client',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50)),
                ('made_by', models.CharField(blank=True, max_length=80)),
                ('link', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name': 'footer',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50)),
                ('head_title', models.CharField(blank=True, max_length=50)),
                ('head_text', models.CharField(blank=True, max_length=80)),
                ('company_name', models.CharField(max_length=80, unique=True)),
                ('company_slogan', models.CharField(blank=True, max_length=80)),
                ('logo_main', models.FileField(null=True, upload_to='logo_main/')),
                ('logo_head', models.FileField(null=True, upload_to='logo_head/')),
            ],
            options={
                'verbose_name': 'home',
            },
        ),
        migrations.CreateModel(
            name='MainContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50)),
                ('about_us_description', models.TextField(blank=True, max_length=500)),
                ('about_us_photo', models.ImageField(blank=True, upload_to='about_us/about_us_photo')),
                ('team_description', models.TextField(blank=True, max_length=500)),
                ('our_service_description', models.TextField(blank=True, max_length=500)),
                ('our_process_description', models.TextField(blank=True, max_length=500)),
                ('video_link', models.URLField(max_length=250)),
                ('our_projects_description', models.TextField(blank=True, max_length=500)),
                ('contact_description', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'main content',
            },
        ),
        migrations.CreateModel(
            name='OurProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.DecimalField(decimal_places=0, max_digits=2)),
                ('process_title', models.CharField(blank=True, max_length=100)),
                ('process_description', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'process',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=100, unique=True)),
                ('project_name', models.CharField(max_length=50, unique=True)),
                ('project_photo', models.ImageField(blank=True, null=True, upload_to='projects/project_photo')),
            ],
            options={
                'verbose_name': 'project',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(blank=True, max_length=70)),
                ('service_description', models.TextField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=70)),
            ],
            options={
                'verbose_name': 'service',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70)),
                ('link', models.URLField(max_length=250)),
                ('icon', models.CharField(blank=True, max_length=70)),
            ],
            options={
                'verbose_name': 'social media',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(max_length=150, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_member/photo')),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'team member',
            },
        ),
    ]
